### ISSUE TITLE
KeyError of 'UsageCode'

### ISSUE THREAD

**Issue by JerryKon** [PixarAnimationStudios/OpenTimelineIO#1082]
Before opening a bug report, please search open and closed issues to see if the problem has already been addressed. If there is such a report, and your issue is not adequately addressed there, please reference the issues in your new report.

## Bug Report

Please pick one of the following categories:

### Build Problem
```
import opentimelineio as otio
timeline = otio.adapters.read_from_file("my_sample.aaf")
```
Error Output

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/linux_home/kongyingjie/python_lib/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/linux_home/kongyingjie/python_lib/opentimelineio/adapters/adapter.py", line 140, in read_from_file
    **adapter_argument_map
  File "/linux_home/kongyingjie/python_lib/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/linux_home/kongyingjie/python_lib/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 1144, in read_from_file
    top = list(storage.toplevel())
  File "/linux_home/kongyingjie/python_lib/aaf2/content.py", line 42, in toplevel
    if mob.usage == 'Usage_TopLevel':
  File "/linux_home/kongyingjie/python_lib/aaf2/mobs.py", line 65, in usage
    return self['UsageCode'].value
  File "/linux_home/kongyingjie/python_lib/aaf2/core.py", line 332, in __getitem__
    raise KeyError(key)
KeyError: u'UsageCode'

### Incorrect Functionality and General Questions

Seems the error occurs in aaf2 module

## To Reproduce
Install with pip.

Python 2.7
Linux Centos 7

**Comment by JerryKon** [comment]
Noticed that this is caused by a bad aaf file. The code works with normal aaf file.
