### ISSUE TITLE
build_simple_timeline.py example is broken

### ISSUE THREAD

**Issue by nitinkumartech** [PixarAnimationStudios/OpenTimelineIO#1096]
### Build Problem

python build_simple_timeline.py /mnt/e/yt/ex.xml

`Traceback (most recent call last):
  File "test.py", line 87, in <module>
    main()
  File "test.py", line 83, in main
    otio.adapters.write_to_file(tl, args.filepath)
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/__init__.py", line 191, in write_to_file
    return adapter.write_to_file(
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/adapter.py", line 188, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/adapter.py", line 255, in write_to_string
    return self._execute_function(
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1967, in write_to_string
    _build_sequence_for_timeline(
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1276, in wrapper
    elem = func(item, *args, **kwargs)
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1851, in _build_sequence_for_timeline
    _add_stack_elements_to_sequence(
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1905, in _add_stack_elements_to_sequence
    track_elements = _build_top_level_track(track, track_rate, br_map)
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1793, in _build_top_level_track
    _build_item(item, timeline_range, transition_offsets, br_map)
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1747, in _build_item
    return _build_clip_item(
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1276, in wrapper
    elem = func(item, *args, **kwargs)
  File "/home/cypher/miniconda3/envs/edit/lib/python3.8/site-packages/opentimelineio/adapters/fcp_xml.py", line 1637, in _build_clip_item
    _build_rate(clip_item.source_range.start_time.rate)
AttributeError: 'NoneType' object has no attribute 'start_time'`

### Incorrect Functionality and General Questions

Describe the issue here.

## To Reproduce

1. Operating System: WSL2 ubuntu
2. Python version: 3.8
3. OpenTimelineIO release version or commit hash:OpenTimelineIO==0.13.0

## Expected Behavior

I should get an exported fcpx compatible xml

## Logs

If applicable, attach a conplete console log, that show a reproduction of the problem entirely.

**Comment by ssteinbach** [comment]
I'll fire an issue about the FCPXML and EDL adapters.  For now I'm going to make a PR that adds a source_range call to `build_simple_timeline.py` so that it works as advertised.
