### ISSUE TITLE
Kdenlive adapter no longer working

### ISSUE THREAD

**Issue by codingcatgirl** [PixarAnimationStudios/OpenTimelineIO#1159]
### Incorrect Functionality and General Questions

The kdenlive adapter does not seem to work any more. I looked into the python code a bit and it looks like it's expecting the kdenlive project file to look completely different than it does, it's likely that kdenfile has changed their file format and how they handle tracks in it quite significantly.

```
~/Projekte/sonnenblumenvideo/ otioconvert -i sonnenblumenvideo.kdenlive -o sonnenblumenvideo.fcpxml
Traceback (most recent call last):
  File "/usr/bin/otioconvert", line 33, in <module>
    sys.exit(load_entry_point('OpenTimelineIO==0.14.0', 'console_scripts', 'otioconvert')())
  File "/usr/lib/python3.9/site-packages/opentimelineio/console/otioconvert.py", line 263, in main
    result_tl = otio.adapters.read_from_file(
  File "/usr/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 143, in read_from_file
    return adapter.read_from_file(
  File "/usr/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 139, in read_from_file
    result = self._execute_function(
  File "/usr/lib/python3.9/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/usr/lib/python3.9/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 95, in read_from_string
    for maintrack in maintractor.findall('track'):
AttributeError: 'NoneType' object has no attribute 'findall'
```

This problem has also been described here: https://www.mail-archive.com/kde-bugs-dist@kde.org/msg620606.html

## To Reproduce

1. Operating System: Arch LInux – likely doesn't matter
2. Python version: 3.9 - likely doesn't matter
3. OpenTimelineIO release version: 0.14.0
4. Create a project with the newest version of kdenlive (21.08.3 in my case). put in a video or something
5. use the opentimelineio export feature or use otioconvert to try to convert it, get the error message

## Expected Behavior

Should be able to read a kdenlive project file.

## More information

This is probably helpful: https://community.kde.org/Kdenlive/Development/File_format

**Comment by codingcatgirl** [comment]
I found the issue and submitted a pull request.

**Comment by jamesdeluk** [comment]
> I found the issue and submitted a pull request.
> 
> The problem can also be worked around by opening the kdenlive project file in an editor and adding a `global_feed="1"` to the last `<tractor>` tag (which should be the one that includes all the other tractors). It should look like this:
> 
> ```
>  <tractor title="your project name " id="tractorSOMENUMBER" global_feed="1" in="00:00:00.000" out="00:20:34.480">
>   <track producer="black_track"/>
>   <track producer="tractor0"/>
>   ...
>  </tractor>
> ```

Just a heads up, this didn't work for me.

**Comment by apetrynet** [comment]
Hi @jamesdeluk !
I don't think the fix was released yet. #1191 is merged in main so it'll most likely get rolled out with the upcoming 0.15 release. (Don't know the date for that though..)

**Comment by jamesdeluk** [comment]
> Hi @jamesdeluk ! I don't think the fix was released yet. #1191 is merged in main so it'll most likely get rolled out with the upcoming 0.15 release. (Don't know the date for that though..)

I realise that, but if the fix is based on `global_feed="1"`, then it's possible the fix also will not work. That was my thinking anyway :)

**Comment by apetrynet** [comment]
Ah, sorry! I totally misunderstood. :man_facepalming:  Sorry about that. 
Thanks for flagging this. I'm sure someone with their head attached to their shoulders can answer :smile:

**Comment by amakuramio** [comment]
it is back! 
 otioconvert -i j.kdenlive -o a.xml 
Traceback (most recent call last):
  File "/home/d/.local/bin/otioconvert", line 8, in <module>
    sys.exit(main())
  File "/home/d/.local/lib/python3.10/site-packages/opentimelineio/console/otioconvert.py", line 243, in main
    result_tl = otio.adapters.read_from_file(
  File "/home/d/.local/lib/python3.10/site-packages/opentimelineio/adapters/__init__.py", line 137, in read_from_file
    return adapter.read_from_file(
  File "/home/d/.local/lib/python3.10/site-packages/opentimelineio/adapters/adapter.py", line 119, in read_from_file
    result = self._execute_function(
  File "/home/d/.local/lib/python3.10/site-packages/opentimelineio/plugins/python_plugin.py", line 153, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/d.local/lib/python3.10/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 237, in read_from_string
    raise RuntimeError("Can't find main tractor")
