### ISSUE TITLE
.veg (Magix Vegas) support

### ISSUE THREAD

**Issue by Iria-D** [PixarAnimationStudios/OpenTimelineIO#1659]
## Feature Request

Is this a New Feature, or a Proposed Change to existing Behavior?
new feature

## Description

Describe the new feature, or describe the modification to existing behavior, and provide context as necessary to help with understanding how the feature relates to a workflow or functionality.
I would love to be able to convert from and to sony vegas. I like kdenlive but its import and export function does not work at all. and otioconvert dont know how to make it work, says  otioconvert -i j.kdenlive -o a.xml 
Traceback (most recent call last):
  File "/home/d-ri/.local/bin/otioconvert", line 8, in <module>
    sys.exit(main())
  File "/home/---/.local/lib/python3.10/site-packages/opentimelineio/console/otioconvert.py", line 243, in main
    result_tl = otio.adapters.read_from_file(
  File "/home/-i/.local/lib/python3.10/site-packages/opentimelineio/adapters/__init__.py", line 137, in read_from_file
    return adapter.read_from_file(
  File "/home/-/.local/lib/python3.10/site-packages/opentimelineio/adapters/adapter.py", line 119, in read_from_file
    result = self._execute_function(
  File "/home/d-i/.local/lib/python3.10/site-packages/opentimelineio/plugins/python_plugin.py", line 153, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/d-/.local/lib/python3.10/site-packages/opentimelineio_contrib/adapters/kdenlive.py", line 237, in read_from_string
    raise RuntimeError("Can't find main tractor")
RuntimeError: Can't find main tractor

**Comment by reinecke** [comment]
Hi @amakuramio - It looks like maybe there are two separate issues here? We've been moving the adapters out of the core into separate repos. Can you try the [KDE maintained KDENLive adapter](https://github.com/KDE/kdenlive-opentimelineio) and see if that solves the exception you're running into? If that other adapter has issues, that team would be better suited to help out - unfortunately we're not kdenlive experts.

The OpenTimelineIO core team is shifting focus away from adding new adapters so we can concentrate on core enhancements. There is [documentation](https://opentimelineio.readthedocs.io/en/stable/tutorials/write-an-adapter.html?highlight=adapter) about how to create new adapters available - we encourage interested parties to follow that guide. We're always happy to help with guidance, but the team likely won't be adding any new format support to the main library.
