### ISSUE TITLE
25fps.edl does not play in viewer

### ISSUE THREAD

**Issue by cconcolato** [PixarAnimationStudios/OpenTimelineIO#327]
running the viewer with https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/tests/sample_data/25fps.edl I get
```
Traceback (most recent call last):
  File "./console.py", line 222, in <module>
    main()
  File "./console.py", line 213, in main
    window.load(args.input)
  File "./console.py", line 156, in load
    **self.adapter_argument_map
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 141, in read_from_file
    **adapter_argument_map
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 127, in read_from_file
    **adapter_argument_map
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/cmx_3600.py", line 717, in read_from_string
    ignore_timecode_mismatch=ignore_timecode_mismatch
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/cmx_3600.py", line 99, in __init__
    self.parse_edl(edl_string, rate=rate)
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/cmx_3600.py", line 322, in parse_edl
    self.add_clip(line, comments, rate=rate)
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/cmx_3600.py", line 105, in add_clip
    clip_handler = ClipHandler(line, comment_handler.handled, rate=rate)
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/cmx_3600.py", line 349, in __init__
    self.clip = self.make_clip(comment_data)
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/adapters/cmx_3600.py", line 474, in make_clip
    otio.opentime.from_timecode(self.source_tc_out, self.edl_rate)
  File "/Users/cconcolato/oss_code/OpenTimelineIO/opentimelineio/opentime.py", line 606, in from_timecode
    timecode_str, nominal_fps - 1))
ValueError: Frame rate mismatch. Timecode "01:00:01:24" has frames beyond 23.
```
Is that normal?

**Comment by jminor** [comment]
To open a non-24 fps EDL, you need to add `-a rate=25` to the command line arguments for otioview. Unfortunately the EDL format doesn't include enough information to know in advance what rate it uses.
