### ISSUE TITLE
AAF Reader: Various errors on read attempts

### ISSUE THREAD

**Issue by andrewmoore-nz** [PixarAnimationStudios/OpenTimelineIO#470]
Just thought I'd start sharing some of the errors we're seeing when trying to read our test AAFs - some are real world projects, and some are files we've generated ourselves for testing, all from various platforms (Media Composer, Premiere, Final Cut Pro, Resolve). There are some AAFs that will read fine, but we are certainly seeing many that do not. 

**'NoneType' object has no attribute 'name'**
```
Traceback (most recent call last):
  File "/Users/dev/BitBucket/cf5_resources/Scripts/otio_edl_checking.py", line 37, in <module>
    timeline = otio.adapters.read_from_file(edl)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 886, in read_from_file
    result = _transcribe(storage, parent=None, editRate=None, masterMobs=masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 228, in _transcribe
    child = _transcribe(mob, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 235, in _transcribe
    child = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 329, in _transcribe
    child = _transcribe(item.segment, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 311, in _transcribe
    child = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 318, in _transcribe
    child = _transcribe(component, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 190, in _transcribe
    metadata["Name"] = _get_name(item)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 61, in _get_name
    return item.mob.name or "Untitled SourceClip"
AttributeError: 'NoneType' object has no attribute 'name'
```

----

**Sequence returned <class 'aaf2.components.Sequence'> not implemented**
```
Traceback (most recent call last):
  File "/Users/dev/BitBucket/cf5_resources/Scripts/otio_edl_checking.py", line 37, in <module>
    timeline = otio.adapters.read_from_file(edl)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 886, in read_from_file
    result = _transcribe(storage, parent=None, editRate=None, masterMobs=masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 222, in _transcribe
    child = _transcribe(mob, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 235, in _transcribe
    child = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 329, in _transcribe
    child = _transcribe(item.segment, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 242, in _transcribe
    mobs = _find_timecode_mobs(item)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 111, in _find_timecode_mobs
    for c in item.walk():
  File "/Users/dev/BitBucket/Project/Submodules/PyAAF2/aaf2/components.py", line 182, in walk
    for item in segment.walk():
  File "/Users/dev/BitBucket/Project/Submodules/PyAAF2/aaf2/components.py", line 198, in walk
    type(segment)))
NotImplementedError: Sequence returned <class 'aaf2.components.Sequence'> not implemented
```

----

**Walking <class 'aaf2.components.NestedScope'> not implemented**
```
Traceback (most recent call last):
  File "/Users/dev/BitBucket/cf5_resources/Scripts/otio_edl_checking.py", line 37, in <module>
    timeline = otio.adapters.read_from_file(edl)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 886, in read_from_file
    result = _transcribe(storage, parent=None, editRate=None, masterMobs=masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 228, in _transcribe
    child = _transcribe(mob, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 235, in _transcribe
    child = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 329, in _transcribe
    child = _transcribe(item.segment, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 311, in _transcribe
    child = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 318, in _transcribe
    child = _transcribe(component, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 242, in _transcribe
    mobs = _find_timecode_mobs(item)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 111, in _find_timecode_mobs
    for c in item.walk():
  File "/Users/dev/BitBucket/Project/Submodules/PyAAF2/aaf2/components.py", line 211, in walk
    type(segment)))
NotImplementedError: Walking <class 'aaf2.components.NestedScope'> not implemented
```

----

**'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)**
```
Traceback (most recent call last):
  File "/Users/dev/BitBucket/cf5_resources/Scripts/otio_edl_checking.py", line 37, in <module>
    timeline = otio.adapters.read_from_file(edl)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 886, in read_from_file
    result = _transcribe(storage, parent=None, editRate=None, masterMobs=masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 222, in _transcribe
    child = _transcribe(mob, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 235, in _transcribe
    child = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 329, in _transcribe
    child = _transcribe(item.segment, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 462, in _transcribe
    result.name = str(metadata["Name"])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)
```

As a couple of these do return a `NotImplementedError:`, it's pretty likely what might be going on there... a case that simply hasn't been dealt with yet by the looks of it. Would be great to get an idea of if any of these things are being looked at already and/or when they might get implemented. 

As always, happy to provide copies of the files in question for you to look at.

**Comment by jminor** [comment]
Yes, please provide some files we can test with. Ideally small ones we could add as unit tests.

**Comment by andrewmoore-nz** [comment]
Righto... here is an example AAF for each error I've described:

[OTIO_AAFErrors_Examples_190328.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3015555/OTIO_AAFErrors_Examples_190328.zip)

**Comment by jminor** [comment]
I have a fix for the non-ASCII names example (OTIO_AAFError_Ex4_ASCIIEncoding.aaf) See: #475 
and I'm starting to look at the others.

**Comment by jminor** [comment]
@andrewmoore-nz we just landed #475. Can you check that your non-ASCII examples are working better now? I'm still working through the other problems.

**Comment by jminor** [comment]
Two of the other problem AAFs are covered by this upstream PR: https://github.com/markreidvfx/pyaaf2/pull/35

**Comment by andrewmoore-nz** [comment]
Just checked those AAFs that were failing due to the non-ascii characters and all seems to be playing nicely now... that's great. 

As soon as that PyAAF PR is ready to test with I can try it out on our other test files ASAP. Will be excellent to get that stuff coming through. Thanks @jminor!

**Comment by andrewmoore-nz** [comment]
This may already be covered in the fix for dealing with these issues but thought I'd chime in anyway to let you know what I came across.

I was able to get a `NotImplementedError: Sequence returned <class 'aaf2.components.Sequence'> not implemented` error when opening an AAF where all I had done was to simply give the clip in Premiere some data in the `Tapename` metadata field:

![Screen Shot 2019-04-08 at 5 59 57 PM](https://user-images.githubusercontent.com/19657812/55701808-ada56480-5a28-11e9-8ef2-8f89a9b7d4a5.png)

Example AAF attached here:

[ClipTapeFileNameExport_v03_ClipnameTapenameSet.aaf.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3052814/ClipTapeFileNameExport_v03_ClipnameTapenameSet.aaf.zip)

**Comment by andrewmoore-nz** [comment]
Hey @jminor,

Finally had a chance (figured out how) to get your pull request and test and I can confirm that that has fixed two of those issues - the `Sequence` and `NestedScope` errors. Still seeing the `NoneType` error every now and then, but not nearly as often as the other two. 

Would be good to get those changes merged in to the master branch when they're ready.

**Comment by freesonluxo** [comment]
Hm. Strange. That line

advanced_authoring_format.py
```
def _get_name(item):
    if isinstance(item, aaf2.components.SourceClip):
        try:
            return item.mob.name or "Untitled SourceClip"
        except AttributeError:
            return "SourceClip Missing Mob?"
```

is wrapped in a try-except. It should never be throwing an AttributeError. I know you pasted the error before, but can I see a traceback again? Is it an AttributeError?

**Comment by andrewmoore-nz** [comment]
Hey @freesonluxo ,

Testing that particular error again (or, the files that were generating them), I'm now getting a different error, using the latest commit on the master branch. 

Traceback is now looking like:

```
Traceback (most recent call last):
  File "/usr/local/bin/otiocat", line 11, in <module>
    load_entry_point('OpenTimelineIO==0.10.0.dev1', 'console_scripts', 'otiocat')()
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/console/otiocat.py", line 132, in main
    read_adapter_arg_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/console/otiocat.py", line 99, in _otio_compatible_file_to_json_string
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 919, in read_from_file
    result = _transcribe(storage, parent=None, editRate=None, masterMobs=masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 229, in _transcribe
    child = _transcribe(mob, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 236, in _transcribe
    track = _transcribe(slot, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 339, in _transcribe
    child = _transcribe(item.segment, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 328, in _transcribe
    child = _transcribe(component, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 333, in _transcribe
    item, metadata, editRate, masterMobs
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 676, in _transcribe_operation_group
    child = _transcribe(segment, item, editRate, masterMobs)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 249, in _transcribe
    mobs = _find_timecode_mobs(item)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 112, in _find_timecode_mobs
    for c in item.walk():
  File "/Users/dev/BitBucket/Project/Submodules/PyAAF2/aaf2/components.py", line 195, in walk
    if not self.slot:
  File "/Users/dev/BitBucket/Project/Submodules/PyAAF2/aaf2/components.py", line 169, in slot
    return mob.slot_at(slot_id)
  File "/Users/dev/BitBucket/Project/Submodules/PyAAF2/aaf2/mobs.py", line 82, in slot_at
    raise IndexError("No SlotID: %s" % str(slot_id))
IndexError: No SlotID: 2
```

So, to confirm: the file that was previously giving me the `AttributeError: 'NoneType' object has no attribute 'name' error, is now giving me the error/traceback specified above.

**Comment by andrewmoore-nz** [comment]
Hey @jminor , 

Have had another example of an AAF with a non-ascii character that can't be encoded... 

**UnicodeEncodeError: 'ascii' codec can't encode character u'\u2020'**
```
Traceback (most recent call last):
  File "/usr/local/bin/otiocat", line 11, in <module>
    load_entry_point('OpenTimelineIO==0.10.0.dev1', 'console_scripts', 'otiocat')()
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/console/otiocat.py", line 132, in main
    read_adapter_arg_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/console/otiocat.py", line 99, in _otio_compatible_file_to_json_string
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 136, in read_from_file
    **adapter_argument_map
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 931, in read_from_file
    result = _simplify(result)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 735, in _simplify
    return _simplify(thing[0])
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 742, in _simplify
    result = _simplify(thing.tracks)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 755, in _simplify
    thing[c] = _simplify(child)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 755, in _simplify
    thing[c] = _simplify(child)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 755, in _simplify
    thing[c] = _simplify(child)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 755, in _simplify
    thing[c] = _simplify(child)
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio_contrib/adapters/advanced_authoring_format.py", line 820, in _simplify
    result.source_range = result.trimmed_range()
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/core/item.py", line 98, in trimmed_range
    return self.available_range()
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/schema/clip.py", line 98, in available_range
    self
  File "/Users/dev/BitBucket/Project/Submodules/OpenTimelineIO/opentimelineio/schema/clip.py", line 109, in __str__
    self.metadata
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2020' in position 0: ordinal not in range(128)
```

**Comment by ssteinbach** [comment]
If we're still seeing these errors, can we break this issue down into individual errors so we can track them with a bit more of a fine grained approach?

**Comment by andrewmoore-nz** [comment]
I think *some* of these have been addressed, but perhaps not all. I haven't checked for a while but I believe the fix that we ended up using for the `Sequence` and `NestedScope` issues came from @jminor 's PyAAF branch here - https://github.com/jminor/pyaaf2/tree/selector

Probably easiest to close this for now and re-address any still standing issues once my PR has landed with the necessary fixes for the timecode issues.
