### ISSUE TITLE
Improve unboxing experience for users without cmake installed

### ISSUE THREAD

**Issue by reinecke** [PixarAnimationStudios/OpenTimelineIO#666]
Right now, if a user does not have cmake installed and they try to install, they receive a very verbose message (see example at end of ticket).

Ideally, users would:
1. receive a very short and friendly message telling them they should install cmake
2. have wheels provided for the majority of common platforms to make sure they don't encounter this

Question: Can cmake produce something like a Makefile that we include to avoid having a dependency on cmake for source installs?

example message:

```
Installing collected packages: opentimelineio
  Running setup.py install for opentimelineio ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/username/dev/otiowheel/venv-otiowheel/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py'"'"'; __file__='"'"'/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-record-889gs1ef/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/dev/otiowheel/venv-otiowheel/include/site/python3.8/opentimelineio
         cwd: /private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/
    Complete output (169 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    copying src/py-opentimelineio/opentimelineio/test_utils.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    copying src/py-opentimelineio/opentimelineio/opentime.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    copying src/py-opentimelineio/opentimelineio/hooks.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    copying src/py-opentimelineio/opentimelineio/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    copying src/py-opentimelineio/opentimelineio/media_linker.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    copying src/py-opentimelineio/opentimelineio/exceptions.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    copying src/py-opentimelineio/opentimelineio/core/_core_utils.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    copying src/py-opentimelineio/opentimelineio/core/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    copying src/py-opentimelineio/opentimelineio/core/mediaReference.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    copying src/py-opentimelineio/opentimelineio/core/composable.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    copying src/py-opentimelineio/opentimelineio/core/composition.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    copying src/py-opentimelineio/opentimelineio/core/item.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/core
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/plugins
    copying src/py-opentimelineio/opentimelineio/plugins/manifest.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/plugins
    copying src/py-opentimelineio/opentimelineio/plugins/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/plugins
    copying src/py-opentimelineio/opentimelineio/plugins/python_plugin.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/plugins
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/algorithms
    copying src/py-opentimelineio/opentimelineio/algorithms/track_algo.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/algorithms
    copying src/py-opentimelineio/opentimelineio/algorithms/stack_algo.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/algorithms
    copying src/py-opentimelineio/opentimelineio/algorithms/timeline_algo.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/algorithms
    copying src/py-opentimelineio/opentimelineio/algorithms/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/algorithms
    copying src/py-opentimelineio/opentimelineio/algorithms/filter.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/algorithms
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    copying src/py-opentimelineio/opentimelineio/adapters/otio_json.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    copying src/py-opentimelineio/opentimelineio/adapters/adapter.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    copying src/py-opentimelineio/opentimelineio/adapters/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    copying src/py-opentimelineio/opentimelineio/adapters/cmx_3600.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    copying src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/timeline.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/track.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/transition.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/external_reference.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/serializable_collection.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/schemadef.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/marker.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/stack.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/clip.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/generator_reference.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/effect.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    copying src/py-opentimelineio/opentimelineio/schema/foo.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schema
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schemadef
    copying src/py-opentimelineio/opentimelineio/schemadef/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/schemadef
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/otiostat.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/otiocat.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/otioconvert.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/console_utils.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/otiopluginfo.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/autogen_plugin_documentation.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    copying src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/console
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/console.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/ruler_widget.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/timeline_widget.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/details_widget.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/settings.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    copying src/opentimelineview/track_widgets.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineview
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib
    copying contrib/opentimelineio_contrib/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/kdenlive.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/extern_rv.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/advanced_authoring_format.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/ffmpeg_burnins.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/extern_maya_sequencer.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/fcpx_xml.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/maya_sequencer.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/rv.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/xges.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/ale.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/hls_playlist.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    copying contrib/opentimelineio_contrib/adapters/burnins.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters/aaf_adapter
    copying contrib/opentimelineio_contrib/adapters/aaf_adapter/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters/aaf_adapter
    copying contrib/opentimelineio_contrib/adapters/aaf_adapter/aaf_writer.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters/aaf_adapter
    running egg_info
    writing OpenTimelineIO.egg-info/PKG-INFO
    writing dependency_links to OpenTimelineIO.egg-info/dependency_links.txt
    writing entry points to OpenTimelineIO.egg-info/entry_points.txt
    writing requirements to OpenTimelineIO.egg-info/requires.txt
    writing top-level names to OpenTimelineIO.egg-info/top_level.txt
    reading manifest file 'OpenTimelineIO.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'CHANGELOG.md'
    no previously-included directories found matching 'docs'
    warning: no previously-included files found matching '.gitmodules'
    warning: no previously-included files matching '*.git' found under directory 'src'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'readthedocs-conda.yml'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.gitlab-ci.yml'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '*.pdf'
    warning: no previously-included files found matching 'CODE_OF_CONDUCT.md'
    warning: no previously-included files found matching 'CONTRIBUTING.md'
    warning: no previously-included files found matching 'contrib/opentimelineio_contrib/adapters/Makefile'
    warning: no previously-included files found matching 'Makefile'
    no previously-included directories found matching 'contrib/opentimelineio_contrib/adapters/tests'
    no previously-included directories found matching 'tests'
    no previously-included directories found matching 'src/deps/pybind11/tools/clang'
    no previously-included directories found matching 'src/deps/rapidjson/thirdparty'
    writing manifest file 'OpenTimelineIO.egg-info/SOURCES.txt'
    copying src/py-opentimelineio/opentimelineio/adapters/builtin_adapters.plugin_manifest.json -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio/adapters
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/application_plugins
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/application_plugins/rv
    creating build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/application_plugins/rv/example_otio_reader
    copying contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/PACKAGE -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/application_plugins/rv/example_otio_reader
    copying contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/example_otio_reader_plugin.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/application_plugins/rv/example_otio_reader
    copying contrib/opentimelineio_contrib/application_plugins/rv/example_otio_reader/otio_reader.py -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/application_plugins/rv/example_otio_reader
    copying contrib/opentimelineio_contrib/adapters/contrib_adapters.plugin_manifest.json -> build/lib.macosx-10.9-x86_64-3.8/opentimelineio_contrib/adapters
    running build_ext
    Traceback (most recent call last):
      File "/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py", line 171, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py", line 358, in <module>
        setup(
      File "/Users/username/dev/otiowheel/venv-otiowheel/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py", line 140, in run
        install.run(self)
      File "/Users/username/dev/otiowheel/venv-otiowheel/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py", line 173, in run
        raise RuntimeError(
    RuntimeError: CMake must be installed to build the following extensions: _opentimelineio, _opentime
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/username/dev/otiowheel/venv-otiowheel/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py'"'"'; __file__='"'"'/private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-install-di_hdnwz/opentimelineio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/gw/8vl6g7s91dq3sshvy3hqtftc0000gn/T/pip-record-889gs1ef/install-record.txt --single-version-externally-managed --compile --install-headers /Users/username/dev/otiowheel/venv-otiowheel/include/site/python3.8/opentimelineio Check the logs for full command output.
```

**Comment by meshula** [comment]
C̬̙̹̠̙͖̞̱̀͝u҉͔̗̦̹͢ͅr̥̺̘̩͇͘͢͝s͔̭̫̹̹̫e̷̤̪̩͈͚͔̕͜d̶̖͖̣̻͓̫̻̀͞ ͞ͅi̶̟͈̠̤̮̻̟̘͝s͏͖͎̻̙͎̼͕̺͚͜ș̰̣̹ͅu̴̴҉̰̟̪̖̜̰e̴̷̢̫̖̙̬̙

**Comment by meshula** [comment]
1. Totally agree that the install script should validate that cmake is installed and functional. The USD build script has a function we could lift for that purpose.

2. You definitely do not want to get in the game of distributing a shadow make file, because the makefiles must be baked out per platform.

3. Yes cmake outputs makefiles, but they are deeply, deeply nested sets of files and scripts, and are not position independent.

**Comment by reinecke** [comment]
Updated the issue to strikethrough the Makefile idea. I figured it would be the case that they'd be a bit overbaked for wide consumption but I didn't have enough experience to say :)

**Comment by meshula** [comment]
We have had a cmake/make two headed monster on OpenEXR, and we've been dragging the userbase kicking and screaming to Cmake only. It was starting to feel like 90% of our support burden was bit rotted autoconf scripts on really old linux distributions, so we finally initiated pulling the plug, sloooooowly

**Comment by reinecke** [comment]
Yeah, given your experience I think we need to keep things simple given this project's size. I think our best bet for this is to see if we can get most our user base covered with pre-built wheels and fill in the last bit with good messaging to lead them to success when building from source.

**Comment by JeanChristopheMorinRodeoFX** [comment]
Hey, so packing wise, yes it would be great to have wheels in pypi. Though, if you do so, please make sure the wheels are compliant with the different manylinux PEPS. Also, I'd make sure the built wheels are passing the checks available with https://github.com/pypa/auditwheel .

Last thing, the binaries should be linked with relative paths, not absolute paths. Right now if we build a wheel for OpenTimelineIO and use ldd to check the generated binaries, it shows that it's well using RPATHs, but with absolute paths... So it makes the wheel completely unusable. (That because of https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio-bindings/CMakeLists.txt#L18. `CMAKE_INSTALL_PREFIX` is an absolute path).

Thanks :) And let me know if you have any questions regarding auditwheel or what kind of problems we encountered with the wheels produced with the 0.12.0 version of OpenTimelineIO (I'm not an expert with this package, but I know the Python packaging ecosystem pretty well).

**Comment by reinecke** [comment]
@JeanChristopheMorinRodeoFX that's great info! I actually have some manylinux wheels up for test right now. If you have a linux setup, would you mind giving them a try?

You can test by running this command: `pip install --index-url https://test.pypi.org/simple/  opentimelineio==0.12.0`

Thanks!

**Comment by reinecke** [comment]
Also, for more detail, the wheels were built in the docker image `quay.io/pypa/manylinux1_x86_64` using each python available in `/opt/python` and each wheel was then made manylinux compliant using a command like `auditwheel repair OpenTimelineIO-0.12.0-cp37-cp37m-linux_x86_64.whl --plat manylinux1_x86_64`.

I believe the repair fixes any binary pathing issues, but I'm not totally sure.

**Comment by JeanChristopheMorinRodeoFX** [comment]
@reinecke I'm quite happy that you already used the right tools! I've tried the `cp27-cp27mu-manylinux1_x86_64` on linux (CentOS-7.6) and it seems to be working (I personally don't know how to use OTIO,  so I'll have to ask my team to test if it works for them). Will get back to you quite soon on this.

I also took the liberty of testing the OSX wheel. Unfortunately, it doesn't work.
```(.venv) (bash)[jcmorin@wrk777d~otio]$ otool -L .venv/lib/python2.7/site-packages/opentimelineio/_opentime.so
.venv/lib/python2.7/site-packages/opentimelineio/_opentime.so:
	@rpath/libopentimelineio.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libopentime.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
(.venv) (bash)[jcmorin@wrk777d~otio]$ otool -l .venv/lib/python2.7/site-packages/opentimelineio/_opentime.so | grep RPATH -B 1 -A 2
Load command 15
          cmd LC_RPATH
      cmdsize 144
         path /usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/opentimelineio/cxx-libs/lib (offset 12)
```

If I search for `libopentime`, I simply can't find it. And in the `dist-info/RECORD`, I don't see the lib in there.

> I believe the repair fixes any binary pathing issues, but I'm not totally sure.
I think I would still make sure RPATH is using relative paths, just to be extra sure if people needs to create wheels by themselves.

**Comment by JeanChristopheMorinRodeoFX** [comment]
I forget to ask, but are you planning to ship a wheel for OSX 10.13? Also, by curiosity, you will use GitHub actions to build the wheels or Travis? Or you built them locally on a machine?

**Comment by reinecke** [comment]
Hey @JeanChristopheMorinRodeoFX, thanks for getting back!

I'm aware of the issue with the OS X one, looking to some alternate approaches to see if I can address it. I'm still evaluating to see how realistic it is to provide wheels for macos.

For the moment, I'm building the wheels locally. That's clearly not a scalable or ideal thing to do. My goal is to automate producing those artifacts sooner than later.

My current hope is that I can have manylinux x86_64 wheels for release 0.12.0. As I work out how to produce good wheels for other platforms, I may supplement that release over time.

Are there specific platforms you use that would be helpful to have wheels for?

**Comment by JeanChristopheMorinRodeoFX** [comment]
>I'm aware of the issue with the OS X one, looking to some alternate approaches to see if I can address it. I'm still evaluating to see how realistic it is to provide wheels for macos.

It should be more realistic than building wheels on Windows I think 😛 If you need help, let me know. I have some free time at night because I'm currently in quarantine (we are probably multiple in this situation 😛 ).

>Are there specific platforms you use that would be helpful to have wheels for?

 If I speak on behalf of the company I work for (RodeoFX), we use Linux and OSX. We don't support Windows in our pipeline. But we are lucky enough to have resources to build wheels when necessary. Though it's always nice when the wheels are provided by the package maintainers themselves. If I speak for the general average size (and smaller ones) studios, I'd say probably the three platforms.

**Comment by reinecke** [comment]
@JeanChristopheMorinRodeoFX I uploaded some new mac wheels to test, if you want to give them a try. Because of name reuse restrictions, they're a bit weird so you can do this:
`pip install --index-url https://test.pypi.org/simple/ opentimelineio==0.12.0.test`

In the prod pypi I'll use the correct names.

**Comment by JeanChristopheMorinRodeoFX** [comment]
From the look of it, the OSX 10.13 wheel seems to work. At least I can install it and import `opentimelineio._otio`. Its `LC_RPATH` looks weird (it points to the system's python install), but there is two `LC_LOAD_DYLIB` which point at the right path.

```
Load command 9
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name @loader_path/.dylibs/libopentimelineio.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @loader_path/.dylibs/libopentime.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 15
          cmd LC_RPATH
      cmdsize 120
         path /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/opentimelineio/cxx-libs/lib (offset 12)
```

>Edit: also, these are largely built against the 10.13 SDK so they get much more coverage across OS versions

Perfect.

**Comment by reinecke** [comment]
After testing across several environments and users (thanks @JeanChristopheMorinRodeoFX  and @mjoblin), I went ahead and pushed these wheels to 0.12.0. If we feel pretty good about how this is working for this release, we'll look at integrating it with CI.

More detail on the OS X wheels:
They were built in a clean qemu virtual machine running Mac OS Sierra.

Assuming my notes have all the steps correct, this is what I did within the clean build VM:

- Installed Python 3.8 from the python.org download
- `xcode-select --install` to install the command-line tools package
- installed homebrew
- `brew install cmake` to install cmake
- `python3.8 -m venv buildenv` and `source buildenv/bin/activate` to create a build env
- `python -m pip install cibuildwheel==1.3.0`
- `git clone https://github.com/PixarAnimationStudios/OpenTimelineIO.git`
- `cd OpenTImelineIO`
- `git checkout "tags/v0.12"`
- `git submodule update --init --recursive`
- `CIBW_PLATFORM=macos python3 -m cibuildwheel`
- Copied out the `wheelhouse` directory and used twine to push from my machine

**Comment by reinecke** [comment]
In #667 @Celeborn2BeAlive has this script for windows wheel building: https://gist.github.com/Celeborn2BeAlive/f6a475e863726d767a6a0669c692e90e

This, along with the above instructions for Mac and Linux should be ported to GitHub actions.

**Comment by reinecke** [comment]
Capturing some discussion notes from PRs and elsewhere about how to address some of the windows wheel building below.

For windows, I'm pretty certain we need to at least pull:

https://github.com/pybind/cmake_example/blob/6de957d06a372a7b106e5e3b8e29b97a8ec3afc7/setup.py#L10-L15

and:

https://github.com/pybind/cmake_example/blob/6de957d06a372a7b106e5e3b8e29b97a8ec3afc7/setup.py#L73

And replace this:

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/db9996779cc80bf4268d0c3b2f1f8f80cfd55154/setup.py#L129-L130

@meshula notes:
> also see this confusing stuff: https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/build_scripts/build_usd.py#L337

> Notice that VS2019 and greater has an inconvenient new incompatible syntax.
> There's a wodge of code here that detects the species of Visual Studio in the active build environment: https://github.com/PixarAnimationStudios/USD/blob/090ef0d849ced875b3b99a15e454b69148ccd8e1/build_scripts/build_usd.py#L133

and:
> per usd_build.py, we should detect VS2019 or greater, as this argument doesn't apply for VS2017 and less, where 64 bit builds are indicated by appending "Win64" to the build target.

@ssteinbach notes:
> VFX Platform seems to support minimum vs2017 across the board, FWIW

**Comment by reinecke** [comment]
Also note, macOS 11 could be tricky as GitHub doesn't have runners widely available yet: https://github.com/actions/virtual-environments/issues/2486

Perhaps we should shard a new ticket for that.
