### ISSUE TITLE
Is there anything I need to know when convert to fcpxml timelines

### ISSUE THREAD

**Issue by lionf96** [PixarAnimationStudios/OpenTimelineIO#741]
I can successfully convert a kedenlive timeline to OTIO format. However converting to fcpxml results in errors. I even tried converting the otio file into fcpxml and still get the same errors. The otio file and kdenlive files open up just fine in otioview. Ca anyone help with the issue I'm having. Below is the error.

Traceback (most recent call last):
  File "/usr/local/bin/otioconvert", line 11, in <module>
    load_entry_point('OpenTimelineIO==0.13.0.dev1', 'console_scripts', 'otioconvert')()
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio/console/otioconvert.py", line 266, in main
    **write_adapter_arg_map
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio/adapters/__init__.py", line 194, in write_to_file
    **adapter_argument_map
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio/adapters/adapter.py", line 182, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio/adapters/adapter.py", line 246, in write_to_string
    **adapter_argument_map
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 1182, in write_to_string
    return FcpxOtio(input_otio).to_xml()
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 193, in to_xml
    top_sequence = self._stack_to_sequence(project.tracks)
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 265, in _stack_to_sequence
    self._track_for_spine(track, idx, spine, compound_clip)
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 290, in _track_for_spine
    self._find_or_create_format_from(track).get("id")
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 315, in _find_parent_element
    self._frame_rate_from_element(item, format_id)
  File "/usr/local/lib/python3.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 368, in _frame_rate_from_element
    total, rate = format_element.get("frameDuration").split("/")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by apetrynet** [comment]
Looks like there might be a conflict between how kdenlive and fcpxml store frame rates. The fcpxml adapter is expecting a rational number string it can split on "/". So you have a simple source file we can look at?

**Comment by lionf96** [comment]
I attached a simplified version of my kdenlive project. 

[test.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/4846772/test.zip)

**Comment by lionf96** [comment]
I forgot to include the otio export that works. I case you also want to look at it. Thank you for your help.
[Archive.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/4847180/Archive.zip)

**Comment by apetrynet** [comment]
I'm not in front of my machine so can't test ATM but the values in the otio file's durations look a bit off. A wild guess of the top of my head might be that this is a division rounding issue in python 2 vs 3. Are you able to test the same conversions in a python 2 environment?
Perhaps the authors of the kdenlive and fcpxml adapters have some input?

**Comment by lionf96** [comment]
I just tried with Python2 and recieved the same errors.

Traceback (most recent call last):
  File "/usr/local/bin/otioconvert", line 11, in <module>
    load_entry_point('OpenTimelineIO==0.13.0.dev1', 'console_scripts', 'otioconvert')()
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio/console/otioconvert.py", line 266, in main
    **write_adapter_arg_map
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio/adapters/__init__.py", line 194, in write_to_file
    **adapter_argument_map
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio/adapters/adapter.py", line 182, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio/adapters/adapter.py", line 246, in write_to_string
    **adapter_argument_map
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 1182, in write_to_string
    return FcpxOtio(input_otio).to_xml()
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 193, in to_xml
    top_sequence = self._stack_to_sequence(project.tracks)
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 265, in _stack_to_sequence
    self._track_for_spine(track, idx, spine, compound_clip)
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 290, in _track_for_spine
    self._find_or_create_format_from(track).get("id")
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 315, in _find_parent_element
    self._frame_rate_from_element(item, format_id)
  File "/usr/local/lib/python2.7/dist-packages/opentimelineio_contrib/adapters/fcpx_xml.py", line 368, in _frame_rate_from_element
    total, rate = format_element.get("frameDuration").split("/")
ValueError: need more than 1 value to unpack

**Comment by apetrynet** [comment]
Ok, does the otio file contain values with decimals in the duration like the other one?

**Comment by lionf96** [comment]
Yes, looking through the otio file I see decimal values.

I'm not much of a python coder but I put some print statements to get the values stored in format_element before "frameDuration" is split. I added the #'s to the print statement to make sure no extra spaces appeared. Below are the values.

FrameDuration: ##
id: #r1#
name: #FFVideoFormat1080p29.97002997002997#

I saw that the FRAMERATE_FRAMEDURATION array didnt have an entry for 29.97002997002997. So I added it and uses the same value for 29.97. The export worked after I did that.

**Comment by reinecke** [comment]
Looking at the context (https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/1468491b98ae588ad537ee557d27ace022d1d563/contrib/opentimelineio_contrib/adapters/fcpx_xml.py#L368-L370), this looks like it might be a good use case for the fractions module:

```
>>> from fractions import Fraction
>>> raw_frame_duration = "1001/24000s"
>>> duration_fraction = Fraction("1001/24000s".replace("s", ""))
>>> rate_fraction = 1 / duration_fraction
>>> float(rate_fraction)
23.976023976023978
```

Also, another note. I'm not super familiar with the format, but on this line (https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/1468491b98ae588ad537ee557d27ace022d1d563/contrib/opentimelineio_contrib/adapters/fcpx_xml.py#L370) frame rates are being forced to integer. Is that correct?

**Comment by lionf96** [comment]
I don't think it's a conversion issue. line 368 in fcpx_xml.py is getting an empty value because the framerate "23.976023976023978" does not exist. I attached a screenshot where I added the framerate to get the export to work.

![Screenshot 2020-06-29 at 3 51 51 PM](https://user-images.githubusercontent.com/39504083/86049812-cf6d7b80-ba20-11ea-88f6-1656d793d740.png)

**Comment by reinecke** [comment]
Also worth noting, matching float frame rates will cause problems. The actual SMPTE definition for NSTC 29.97fps is exactly 30000/1001 fps. For 23.976 (or 23.98 colloquially) is 24000/1001fps. 59.94 is actually 60000/1001.

I have this piece of code I've been copy/pasting around, I just haven't gotten a chance to integrate it back to somewhere in OTIO:
```
def rate_fraction_from_float(rate: float) -> Fraction:
    """
    Given a frame rate float, creates a frame rate fraction conforming to known
    good rates where possible. This will do fuzzy matching of
    23.98 to 24000/1001, for instance.
    """
    # Whole numbers are easy
    if isinstance(rate, int) or rate.is_integer():
        return Fraction(rate)

    NTSC_RATES = (
        Fraction(24000, 1001),
        Fraction(30000, 1001),
        Fraction(60000, 1001),
    )
    for ntsc_rate in NTSC_RATES:
        # The tolerance of 0.004 comes from 24000/1001 - 23.98
        if abs(rate - ntsc_rate) < 0.004:
            return ntsc_rate

    return Fraction(rate)
```

**Comment by reinecke** [comment]
ahh, so the more robust way to achieve the `FRAMERATE_FRAMEDURATION` mapping is probably to use the `rate_fraction_from_float` function I posted previously to get the rate into a `Fraction`, then use some code like this to generate the frame duration string:
```
rate_string = "{}s".format(1 / rate_fraction)
```
