### ISSUE TITLE
Multiple errors when trying to install (I'm probably not doing something right)

### ISSUE THREAD

**Issue by garsh1** [PixarAnimationStudios/OpenTimelineIO#754]
Collecting dlib
  Using cached dlib-19.20.0.tar.gz (3.2 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\harmon\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Harmon\AppData\Local\Temp\pip-wheel-dot99eng'
       cwd: C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=c:\users\harmon\appdata\local\programs\python\python37\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\build\lib.win-amd64-3.7 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:3 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Harmon/AppData/Local/Temp/pip-install-pwjj0oo2/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\setup.py", line 135, in run
      self.build_extension(ext)
    File "C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "c:\users\harmon\appdata\local\programs\python\python37\lib\subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=c:\\users\\harmon\\appdata\\local\\programs\\python\\python37\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\harmon\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Harmon\AppData\Local\Temp\pip-record-f81gg7ql\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\harmon\appdata\local\programs\python\python37\Include\dlib'
         cwd: C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\
    Complete output (57 lines):
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=c:\users\harmon\appdata\local\programs\python\python37\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\build\lib.win-amd64-3.7 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Harmon/AppData/Local/Temp/pip-install-pwjj0oo2/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\setup.py", line 135, in run
        self.build_extension(ext)
      File "C:\Users\Harmon\AppData\Local\Temp\pip-install-pwjj0oo2\dlib\setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\users\harmon\appdata\local\programs\python\python37\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=c:\\users\\harmon\\appdata\\local\\programs\\python\\python37\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\harmon\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Harmon\\AppData\\Local\\Temp\\pip-install-pwjj0oo2\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Harmon\AppData\Local\Temp\pip-record-f81gg7ql\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\harmon\appdata\local\programs\python\python37\Include\dlib' Check the logs for full command output.

**Comment by garsh1** [comment]
Never mind I think I’ve figured it out.
