### ISSUE TITLE
CMX 3600 - Framerate mismatch error seems to be giving incorrect "beyond" value

### ISSUE THREAD

**Issue by reinecke** [PixarAnimationStudios/OpenTimelineIO#759]
When the CMX parser finds an EDL rate mismatch, it reports `0.000000` instead of the rate the parser was using:
```
$ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:03)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opentimelineio as otio
>>> otio.adapters.read_from_file("tests/sample_data/25fps.edl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/__init__.py", line 144, in read_from_file
    **adapter_argument_map
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/adapter.py", line 133, in read_from_file
    **adapter_argument_map
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/plugins/python_plugin.py", line 174, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/cmx_3600.py", line 756, in read_from_string
    ignore_timecode_mismatch=ignore_timecode_mismatch
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/cmx_3600.py", line 108, in __init__
    self.parse_edl(edl_string, rate=rate)
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/cmx_3600.py", line 348, in parse_edl
    self.add_clip(line, comments, rate=rate)
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/cmx_3600.py", line 114, in add_clip
    clip_handler = ClipHandler(line, comment_handler.handled, rate=rate)
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/cmx_3600.py", line 375, in __init__
    self.clip = self.make_clip(comment_data)
  File "/Users/reinecke/envs/otiotest/lib/python3.7/site-packages/opentimelineio/adapters/cmx_3600.py", line 504, in make_clip
    opentime.from_timecode(self.source_tc_out, self.edl_rate)
ValueError: Frame rate mismatch.  Timecode '01:00:01:24' has frames beyond 0.000000
```

This also applies when giving a specific rate as an adapter argument.

**Comment by nclaveeoh** [comment]
I came across the same issue and got it to work by doing the following:

```
fps=25
otio.adapters.read_from_file(timeline_file, rate=fps)
```

**Comment by ssteinbach** [comment]
Correct.  I believe (could be wrong) that CMX EDLs don't have a way of specifying their frame rate, so OTIO needs to be told what the rate is.  I think this issue is that the error message the adapter emits should suggest that the solution is setting the rate adapter argument (which is not super discoverable).

**Comment by reinecke** [comment]
Fixed by #795.

Validated using the above test code with git revision `44f8ce8e0d39cf5f4a7aa2d45879655810a8a56a` and got this result:

`ValueError: Frame rate mismatch.  Timecode '01:00:01:24' has frames beyond 23`

**Comment by TrevorAyl** [comment]
```
otioview /Users/***/Downloads/Sample\ for\ OTIO/Exports/OTIO\ OPAtom\ Native\ 16ch.edl
Traceback (most recent call last):
  File "/Users/***/Documents/GitHub/otioenv/bin/otioview", line 8, in <module>
    sys.exit(main())
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineview/console.py", line 301, in main
    window.load(args.input)
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineview/console.py", line 191, in load
    file_contents = otio.adapters.read_from_file(
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/adapters/__init__.py", line 137, in read_from_file
    return adapter.read_from_file(
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/adapters/adapter.py", line 110, in read_from_file
    result = self._execute_function(
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/plugins/python_plugin.py", line 142, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/adapters/cmx_3600.py", line 791, in read_from_string
    parser = EDLParser(
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/adapters/cmx_3600.py", line 93, in __init__
    self.parse_edl(edl_string, rate=rate)
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/adapters/cmx_3600.py", line 357, in parse_edl
    self.add_clip(
  File "/Users/***/Documents/GitHub/otioenv/lib/python3.9/site-packages/opentimelineio/adapters/cmx_3600.py", line 129, in add_clip
    record_out = opentime.from_timecode(
ValueError: Frame rate mismatch.  Timecode '01:00:09:24' has frames beyond 23
```

Still seems to be an issue - going to try some of the workarounds but thought I'd drop this in here. Be good if it analysed and said 'xx' appears to be the highest frame number (which would give a clue as to what the frame rate of the EDL is). 



```
TITLE:   OTIO OPAtom Native 16ch 
FCM: NON-DROP FRAME
000001  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:04:19 00:00:05:20 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:04:19 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000002  2020_16CH_IDENT.WAV                                                                                                               A2    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000003  2020_16CH_IDENT.WAV                                                                                                               A3    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000004  2020_16CH_IDENT.WAV                                                                                                               A4    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000005  2020_16CH_IDENT.WAV                                                                                                               A5    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000006  2020_16CH_IDENT.WAV                                                                                                               A6    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000007  AX                               A7    C        00:00:00:00 00:00:02:10 01:00:00:00 01:00:01:00 
M2      AX                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000008  2020_16CH_IDENT.WAV                                                                                                               A8    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000009  2020_16CH_IDENT.WAV                                                                                                               A9    C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000010  2020_16CH_IDENT.WAV                                                                                                               A10   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000011  2020_16CH_IDENT.WAV                                                                                                               A11   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000012  2020_16CH_IDENT.WAV                                                                                                               A12   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000013  2020_16CH_IDENT.WAV                                                                                                               A13   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000014  2020_16CH_IDENT.WAV                                                                                                               A14   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000015  2020_16CH_IDENT.WAV                                                                                                               A15   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000016  2020_16CH_IDENT.WAV                                                                                                               A16   C        00:00:00:00 00:00:01:01 01:00:00:00 01:00:01:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:00:00 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000017  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:10:15 00:00:11:16 01:00:01:00 01:00:02:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:10:15 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 2 TO RECORD 1
000018  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:15:14 00:00:16:15 01:00:02:00 01:00:03:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:15:14 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 3 TO RECORD 1
000019  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:20:14 00:00:21:15 01:00:03:00 01:00:04:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:20:14 
*OTHER, TIME COMPRESSION EXPANSION 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 4 TO RECORD 1
000020  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:26:09 00:00:27:10 01:00:04:00 01:00:05:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:26:09 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 5 TO RECORD 1
000021  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:31:04 00:00:32:05 01:00:05:00 01:00:06:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:31:04 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 6 TO RECORD 1
000022  AX                               A     C        00:00:13:22 00:00:16:08 01:00:06:00 01:00:07:00 
M2      AX                                        059.9 00:00:13:22 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV
000023  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:41:14 00:00:41:19 01:00:07:00 01:00:07:04 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:41:14 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 8 TO RECORD 1
000024  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:41:20 00:00:42:17 01:00:07:04 01:00:08:00 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:41:20 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 8 TO RECORD 1
000025  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:47:01 00:00:49:01 01:00:08:00 01:00:09:24 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:47:01 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 9 TO RECORD 1
000026  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:53:03 00:00:55:02 01:00:09:24 01:00:11:22 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:53:03 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 10 TO RECORD 1
000027  2020_16CH_IDENT.WAV                                                                                                               A     C        00:00:59:02 00:01:00:23 01:00:11:22 01:00:13:17 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:00:59:02 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 11 TO RECORD 1
000028  2020_16CH_IDENT.WAV                                                                                                               A     C        00:01:04:24 00:01:06:20 01:00:13:17 01:00:15:12 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:01:04:24 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 12 TO RECORD 1
000029  2020_16CH_IDENT.WAV                                                                                                               A     C        00:01:10:16 00:01:12:03 01:00:15:12 01:00:16:23 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:01:10:16 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 13 TO RECORD 1
000030  2020_16CH_IDENT.WAV                                                                                                               A     C        00:01:15:14 00:01:17:04 01:00:16:23 01:00:18:12 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:01:15:14 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 14 TO RECORD 1
000031  2020_16CH_IDENT.WAV                                                                                                               A     C        00:01:20:13 00:01:22:04 01:00:18:12 01:00:20:02 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:01:20:13 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 15 TO RECORD 1
000032  2020_16CH_IDENT.WAV                                                                                                               A     C        00:01:25:16 00:01:27:05 01:00:20:02 01:00:21:15 
M2      2020_16CH_IDENT.WAV                                                                                                                        059.9 00:01:25:16 
*FROM CLIP NAME:  59.94 - 2020_16CH_IDENT.WAV 
*PATCH 2020_16CH_IDENT.WAV:  FROM SOURCE 16 TO RECORD 1
000033  16CH_TONE.WAV                                                                                                                     A     C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000034  16CH_TONE.WAV                                                                                                                     A2    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000035  16CH_TONE.WAV                                                                                                                     A3    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000036  16CH_TONE.WAV                                                                                                                     A4    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000037  16CH_TONE.WAV                                                                                                                     A5    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000038  16CH_TONE.WAV                                                                                                                     A6    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000039  16CH_TONE.WAV                                                                                                                     A7    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000040  16CH_TONE.WAV                                                                                                                     A8    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000041  16CH_TONE.WAV                                                                                                                     A9    C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000042  16CH_TONE.WAV                                                                                                                     A10   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000043  16CH_TONE.WAV                                                                                                                     A11   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000044  16CH_TONE.WAV                                                                                                                     A12   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000045  16CH_TONE.WAV                                                                                                                     A13   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000046  16CH_TONE.WAV                                                                                                                     A14   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000047  16CH_TONE.WAV                                                                                                                     A15   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
000048  16CH_TONE.WAV                                                                                                                     A16   C        00:00:00:00 00:00:02:00 01:00:25:24 01:00:27:24 
M2      16CH_TONE.WAV                                                                                                                              050.0 00:00:00:00 
*FROM CLIP NAME:  16CH TONE.WAV
*
* ============================================================
* Marker Metadata
* ------------------------------------------------------------
* 
* Sequence name: OTIO OPAtom Native 16ch
* Number  Color   Marker Name              Start TC    End TC      Duration    Track  Part        Comment
*      1  Red     ***            01:00:03:13                         D1                 Data track marker 1
*      2  Green   ***            01:00:22:10                         D1                 Data track marker 2
*      3  Blue    ***            01:00:25:15                         D1                 Data track marker 3
*      4  Red     ***            01:00:03:13                         V2                 V2 marker on empty track 1
*
*      5  Green   ***            01:00:22:10                         V2                 V2 marker on empty track 2
*      6  Blue    ***            01:00:25:15                         V2                 V2 marker on empty track 3
*
*      7  Green   ***            01:00:22:10                         A1                 A1 marker on empty track 1
*      8  Blue    ***            01:00:25:15                         A1                 A1 marker on empty track 2
*
```

**Comment by reinecke** [comment]
@TrevorAyl I think the message is correct, though I can understand the confusion and I've thought a bit about whether or not the wording could be different.

The message:
```Frame rate mismatch.  Timecode '01:00:09:24' has frames beyond 23```

Could be restated as something like:
```Frame rate mismatch.  24 fps Timecode should have frame numbers between 0 and 23 '01:00:09:24' has frames beyond 23```

In other words, since 24 fps timecode rolls over to `00` after frame `23`, `24` is illegal because it should have gone back to zero at that point.

So I think the message is correct, but the wording is probably confusing.

**Comment by TrevorAyl** [comment]
I was thinking more along the lines of:

>ValueError: Frame rate mismatch. Timecode '01:00:09:24' has frames beyond 23

>This is likely to be because the input has a different frame rate than the default rate used (24 fps).

>e.g. to view a 25 fps edl the command is:
otioview  input.edl -a rate=25

**Comment by reinecke** [comment]
Ahh - I see. Yeah - so this is a bit more of an error message OTIOView could escalate to give additional context around how to resolve the issue.

Of note, otioview is scheduled for deprecation (probably removal in 0.18.0 or 1.0, whichever comes first) and we'll be pushing users toward using `otioconvert` if they need an adapter and then taking the resulting OTIO file to [`raven`](https://github.com/OpenTimelineIO/raven) - though we still have a few things to do before we reach feature parity.

So I think what we'd want to do is:

- Create some examples of how to use otioconvert and raven together
- Add some code to otioconvert to catch some of these common cases and put up more humane errors like you described above
