### ISSUE TITLE
AttributeError: type object 'opentimelineio._opentime.TimeRange' has no attribute 'range_from_start_end_time_inclusive'

### ISSUE THREAD

**Issue by Chadt54** [PixarAnimationStudios/OpenTimelineIO#952]
```
C:\Users\Chad>python -m pip install git+https://github.com/PixarAnimationStudios/OpenTimelineIO.git
Collecting git+https://github.com/PixarAnimationStudios/OpenTimelineIO.git
  Cloning https://github.com/PixarAnimationStudios/OpenTimelineIO.git to c:\users\chad\appdata\local\temp\pip-req-build-g9jqi4a1
  Running command git clone -q https://github.com/PixarAnimationStudios/OpenTimelineIO.git 'C:\Users\Chad\AppData\Local\Temp\pip-req-build-g9jqi4a1'
  Running command git submodule update --init --recursive -q
Requirement already satisfied: pyaaf2~=1.4.0 in c:\users\chad\appdata\local\programs\python\python37\lib\site-packages (from OpenTimelineIO==0.14.0.dev1) (1.4.0)
Installing collected packages: OpenTimelineIO
  Found existing installation: OpenTimelineIO 0.13.0
    Uninstalling OpenTimelineIO-0.13.0:
      Successfully uninstalled OpenTimelineIO-0.13.0
  Running setup.py install for OpenTimelineIO ... done
Successfully installed OpenTimelineIO-0.14.0.dev1
WARNING: You are using pip version 19.2.3, however version 21.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Chad>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opentimelineio as otio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chad\AppData\Local\Programs\Python\Python37\lib\site-packages\opentimelineio\__init__.py", line 35, in <module>
    from . import (
  File "C:\Users\Chad\AppData\Local\Programs\Python\Python37\lib\site-packages\opentimelineio\opentime.py", line 13, in <module>
    range_from_start_end_time_inclusive = TimeRange.range_from_start_end_time_inclusive
AttributeError: type object 'opentimelineio._opentime.TimeRange' has no attribute 'range_from_start_end_time_inclusive'

```

**Comment by ssteinbach** [comment]
This is a function in the `opentime` namespace, not a method on the `TimeRange` class:

```
>>> import opentimelineio as otio
>>> otio.opentime.range_from_start_end_time_inclusive(...)
```

**Comment by ssteinbach** [comment]
Or maybe I'm misunderstanding this bug report.  Is that just happening on import?  On windows w/ python 3.7?

It looks like our CI is passing so is there more context on this?
https://github.com/PixarAnimationStudios/OpenTimelineIO/runs/2422614364?check_suite_focus=true

**Comment by Chadt54** [comment]
What you see above is all that I've done, in it's entirety. I just stumbled upon this project today, and went to try it out and this is what happened.

To answer your question; no more context, this is the full context. Just a Windows 10 machine, using Python 3.7.7

**Comment by ssteinbach** [comment]
Can you try installing from pypi instead of from the GitHub HEAD?

`python -m pip install opentimelineio`

We've been tinkering with the build system so I'm curious to track this down.

Thanks!

**Comment by Chadt54** [comment]
Already tried that (that's why it says "Found existing installation: OpenTimelineIO 0.13.0"). That version doesn't work either, but it has a different error (more serious error; missing libraries).

**Comment by Chadt54** [comment]
This is from pypi

```
C:\Users\Chad>python -m pip install opentimelineio
Collecting opentimelineio
  Downloading https://files.pythonhosted.org/packages/9e/bb/a3b1f7c94b42f20a59a0d5dbc693ebfeb7623f0f86953f0d946595e2b03d/OpenTimelineIO-0.13.0.tar.gz (2.0MB)
     |████████████████████████████████| 2.0MB 3.3MB/s
Collecting pyaaf2==1.4.0 (from opentimelineio)
  Downloading https://files.pythonhosted.org/packages/69/0a/64f466f1517c9e5d63f8d65545aca085a2dfa47d5c0332d5dafea25d7785/pyaaf2-1.4.0.tar.gz (88kB)
     |████████████████████████████████| 92kB ...
Installing collected packages: pyaaf2, opentimelineio
  Running setup.py install for pyaaf2 ... done
  Running setup.py install for opentimelineio ... done
Successfully installed opentimelineio-0.13.0 pyaaf2-1.4.0
WARNING: You are using pip version 19.2.3, however version 21.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Chad>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opentimelineio as otio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chad\AppData\Local\Programs\Python\Python37\lib\site-packages\opentimelineio\__init__.py", line 35, in <module>
    from . import (
  File "C:\Users\Chad\AppData\Local\Programs\Python\Python37\lib\site-packages\opentimelineio\opentime.py", line 1, in <module>
    from . _opentime import ( # noqa
ImportError: DLL load failed: The specified module could not be found.
```
