### ISSUE TITLE
OpenTimelineIO for windows (python-2.7): No module named _opentime

### ISSUE THREAD

**Issue by aguiot** [PixarAnimationStudios/OpenTimelineIO#984]
## Bug Report

Hi,

I'm trying to install the latest version of OpenTimelineIO (for windows python-2.7).
Unfortunately, I'm facing an issue.

### Build Problem

I'm trying to install the latest version of OpenTimelineIO.
It's working perfectly for linux (python-2.7/python-3.7) and for windows (python-3.7), but it fails for windows (python-2.7).

Everything seems okay during the pip install, here is the build log
```powershell
PS C:\>  C:\Python27\python.exe -m pip install git+https://github.com/PixarAnimationStudios/OpenTimelineIO.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no
 longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pi
p can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove suppo
rt for this functionality.
Collecting git+https://github.com/PixarAnimationStudios/OpenTimelineIO.git
  Cloning https://github.com/PixarAnimationStudios/OpenTimelineIO.git to c:\users\containeradministrator\appdata\local\t
emp\pip-req-build-pczwzt
  Running command git clone -q https://github.com/PixarAnimationStudios/OpenTimelineIO.git 'c:\users\containeradministra
tor\appdata\local\temp\pip-req-build-pczwzt'
  Running command git submodule update --init --recursive -q
Collecting pyaaf2~=1.4.0
  Downloading pyaaf2-1.4.0.tar.gz (88 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ  | 81 kB 1.3 MB/s eta 0
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 88 kB 1.1 MB/s
Collecting backports.tempfile
  Downloading backports.tempfile-1.0-py2.py3-none-any.whl (4.4 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ     | 686 kB 2.2 MB/s eta 0:00:0
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 696 kB 2.2 MB/s eta 0:00:0
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 706 kB 2.2 MB/s eta 0:00:0
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ    | 716 kB 2.2 MB/s eta 0:00
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ    | 727 kB 2.2 MB/s eta 0:00
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ   | 737 kB 2.2 MB/s eta 0:
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ   | 747 kB 2.2 MB/s eta 0:
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ   | 757 kB 2.2 MB/s eta 0:
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ  | 768 kB 2.2 MB/s eta
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  | 778 kB 2.2 MB/s eta
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ | 788 kB 2.2 MB/s et
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ | 798 kB 2.2 MB/s et
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ | 808 kB 2.2 MB/s et
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ| 819 kB 2.2 MB/s
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 829 kB 2.2 MB/s

Collecting pathlib2
  Downloading pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting backports.weakref
  Downloading backports.weakref-1.0.post1-py2.py3-none-any.whl (5.2 kB)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting scandir; python_version < "3.5"
  Downloading scandir-1.10.0-cp27-cp27m-win_amd64.whl (20 kB)
Using legacy 'setup.py install' for OpenTimelineIO, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pyaaf2, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: pyaaf2, backports.weakref, backports.tempfile, future, six, scandir, pathlib2, OpenTimeli
neIO
    Running setup.py install for pyaaf2 ... done
    Running setup.py install for future ... done
    Running setup.py install for OpenTimelineIO ... done
Successfully installed OpenTimelineIO-0.14.0.dev1 backports.tempfile-1.0 backports.weakref-1.0.post1 future-0.18.2 pathl
ib2-2.3.5 pyaaf2-1.4.0 scandir-1.10.0 six-1.16.0
```

But the installed version is broken:
```powershell
PS C:\>  C:\Python27\python.exe
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opentimelineio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\opentimelineio\__init__.py", line 35, in <module>
    from . import (
  File "C:\Python27\lib\site-packages\opentimelineio\opentime.py", line 1, in <module>
    from . _opentime import ( # noqa
ImportError: No module named _opentime
```

If we check in C:\Python27\lib\site-packages\opentimelineio, we can find a file `_opentime.cp37-win_amd64.pyd`:
```powershell
PS C:\> ls C:\Python27\lib\site-packages\opentimelineio


    Directory: C:\Python27\lib\site-packages\opentimelineio


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6/10/2021   9:35 AM                adapters
d-----        6/10/2021   9:35 AM                algorithms
d-----        6/10/2021   9:35 AM                console
d-----        6/10/2021   9:35 AM                core
d-----        6/10/2021   9:35 AM                cxx-sdk
d-----        6/10/2021   9:35 AM                plugins
d-----        6/10/2021   9:35 AM                schema
d-----        6/10/2021   9:35 AM                schemadef
-a----        6/10/2021   9:33 AM           2019 exceptions.py
-a----        6/10/2021   9:35 AM           2845 exceptions.pyc
-a----        6/10/2021   9:33 AM           5404 hooks.py
-a----        6/10/2021   9:35 AM           5073 hooks.pyc
-a----        6/10/2021   9:33 AM           6038 media_linker.py
-a----        6/10/2021   9:35 AM           5483 media_linker.pyc
-a----        6/10/2021   9:33 AM          38400 opentime.dll
-a----        6/10/2021   9:33 AM          31582 opentime.lib
-a----        6/10/2021   9:33 AM           1012 opentime.py
-a----        6/10/2021   9:35 AM           1379 opentime.pyc
-a----        6/10/2021   9:34 AM         784896 opentimelineio.dll
-a----        6/10/2021   9:34 AM        1742998 opentimelineio.lib
-a----        6/10/2021   9:33 AM           2032 test_utils.py
-a----        6/10/2021   9:35 AM           1510 test_utils.pyc
-a----        6/10/2021   9:33 AM           2390 url_utils.py
-a----        6/10/2021   9:35 AM           1393 url_utils.pyc
-a----        6/10/2021   9:34 AM         242176 _opentime.cp37-win_amd64.pyd
-a----        6/10/2021   9:35 AM         623616 _otio.cp37-win_amd64.pyd
-a----        6/10/2021   9:33 AM           1523 __init__.py
-a----        6/10/2021   9:35 AM            620 __init__.pyc
```

## To Reproduce

1. Operating System: **Windows 10 **
2. Python version: **2.7.12**
3. Example snippet that demonstrates the issue - **see above**
4. OpenTimelineIO release version or commit hash: **master branch**
5. Compiler information: **The term 'cl' is not recognized as the name of a cmdlet, function, script file, or operable program**

Do you know what could cause that issue, and how we could solve it?
Thanks in advance for your help,

Anthony

**Comment by meshula** [comment]
@aguiot I noticed github automatically close this issue, because #986 should in theory address your issue. If the problem is not solved, please feel free to reopen this.

**Comment by aguiot** [comment]
#986 solved my issue, thanks a lot @meshula
